#include <iostream>
#include <string>
#ifndef COUNTRY_H
#define COUNTRY_H

// Turning the variable name to a string
#define stringify( name ) #name

using namespace std;

/// @brief Deals with CountryEnum conversions
namespace Country {

    /// @brief Number of Countries in the CountryEnum
    int size = 195; 

    /// @brief Countries stored in the passport must be exclusively from this list
    enum class CountryEnum
    {
        Afghanistan,
        Albania,
        Algeria,
        Andorra,
        Angola,
        Antigua_Deps,
        Argentina,
        Armenia,
        Australia,
        Austria,
        Azerbaijan,
        Bahamas,
        Bahrain,
        Bangladesh,
        Barbados,
        Belarus,
        Belgium,
        Belize,
        Benin,
        Bhutan,
        Bolivia,
        Bosnia_Herzegovina,
        Botswana,
        Brazil,
        Brunei,
        Bulgaria,
        Burkina,
        Burundi,
        Cambodia,
        Cameroon,
        Canada,
        Cape_Verde,
        Central_African_Rep,
        Chad,
        Chile,
        China,
        Colombia,
        Comoros,
        Congo,
        Democratic_Republic_of_Congo,
        Costa_Rica,
        Croatia,
        Cuba,
        Cyprus,
        Czech_Republic,
        Denmark,
        Djibouti,
        Dominica,
        Dominican_Republic,
        East_Timor,
        Ecuador,
        Egypt,
        El_Salvador,
        Equatorial_Guinea,
        Eritrea,
        Estonia,
        Ethiopia,
        Fiji,
        Finland,
        France,
        Gabon,
        Gambia,
        Georgia,
        Germany,
        Ghana,
        Greece,
        Grenada,
        Guatemala,
        Guinea,
        Guinea_Bissau,
        Guyana,
        Haiti,
        Honduras,
        Hungary,
        Iceland,
        India,
        Indonesia,
        Iran,
        Iraq,
        Republic_of_Ireland,
        Italy,
        Ivory_Coast,
        Jamaica,
        Japan,
        Jordan,
        Kazakhstan,
        Kenya,
        Kiribati,
        Korea_North,
        Korea_South,
        Kosovo,
        Kuwait,
        Kyrgyzstan,
        Laos,
        Latvia,
        Lebanon,
        Lesotho,
        Liberia,
        Libya,
        Liechtenstein,
        Lithuania,
        Luxembourg,
        Macedonia,
        Madagascar,
        Malawi,
        Malaysia,
        Maldives,
        Mali,
        Malta,
        Marshall_Islands,
        Mauritania,
        Mauritius,
        Mexico,
        Micronesia,
        Moldova,
        Monaco,
        Mongolia,
        Montenegro,
        Morocco,
        Mozambique,
        Myanmar,
        Namibia,
        Nauru,
        Nepal,
        Netherlands,
        New_Zealand,
        Nicaragua,
        Niger,
        Nigeria,
        Norway,
        Oman,
        Pakistan,
        Palau,
        Panama,
        Papua_New_Guinea,
        Paraguay,
        Peru,
        Philippines,
        Poland,
        Portugal,
        Qatar,
        Romania,
        Russian_Federation,
        Rwanda,
        St_Kitts_Nevis,
        St_Lucia,
        Saint_Vincent_the_Grenadines,
        Samoa,
        San_Marino,
        Sao_Tome_Principe,
        Saudi_Arabia,
        Senegal,
        Serbia,
        Seychelles,
        Sierra_Leone,
        Singapore,
        Slovakia,
        Slovenia,
        Solomon_Islands,
        Somalia,
        South_Africa,
        South_Sudan,
        Spain,
        Sri_Lanka,
        Sudan,
        Suriname,
        Swaziland,
        Sweden,
        Switzerland,
        Syria,
        Taiwan,
        Tajikistan,
        Tanzania,
        Thailand,
        Togo,
        Tonga,
        Trinidad_Tobago,
        Tunisia,
        Turkey,
        Turkmenistan,
        Tuvalu,
        Uganda,
        Ukraine,
        United_Arab_Emirates,
        United_Kingdom,
        United_States,
        Uruguay,
        Uzbekistan,
        Vanuatu,
        Vatican_City,
        Venezuela,
        Vietnam,
        Yemen,
        Zambia,
        Zimbabwe
    };

    /// @brief Array to hold the stringified version of each possible value
    const char* countryEnum_to_string[] =
    {
        stringify( Afghanistan ),
        stringify( Albania ),
        stringify( Algeria ),
        stringify( Andorra ),
        stringify( Angola ),
        stringify( Antigua_Deps ),
        stringify( Argentina ),
        stringify( Armenia ),
        stringify( Australia ),
        stringify( Austria ),
        stringify( Azerbaijan ),
        stringify( Bahamas ),
        stringify( Bahrain ),
        stringify( Bangladesh ),
        stringify( Barbados ),
        stringify( Belarus ),
        stringify( Belgium ),
        stringify( Belize ),
        stringify( Benin ),
        stringify( Bhutan ),
        stringify( Bolivia ),
        stringify( Bosnia_Herzegovina ),
        stringify( Botswana ),
        stringify( Brazil ),
        stringify( Brunei ),
        stringify( Bulgaria ),
        stringify( Burkina ),
        stringify( Burundi ),
        stringify( Cambodia ),
        stringify( Cameroon ),
        stringify( Canada ),
        stringify( Cape_Verde ),
        stringify( Central_African_Rep ),
        stringify( Chad ),
        stringify( Chile ),
        stringify( China ),
        stringify( Colombia ),
        stringify( Comoros ),
        stringify( Congo ),
        stringify( Democratic_Republic_of_Congo ),
        stringify( Costa_Rica ),
        stringify( Croatia ),
        stringify( Cuba ),
        stringify( Cyprus ),
        stringify( Czech_Republic ),
        stringify( Denmark ),
        stringify( Djibouti ),
        stringify( Dominica ),
        stringify( Dominican_Republic ),
        stringify( East_Timor ),
        stringify( Ecuador ),
        stringify( Egypt ),
        stringify( El_Salvador ),
        stringify( Equatorial_Guinea ),
        stringify( Eritrea ),
        stringify( Estonia ),
        stringify( Ethiopia ),
        stringify( Fiji ),
        stringify( Finland ),
        stringify( France ),
        stringify( Gabon ),
        stringify( Gambia ),
        stringify( Georgia ),
        stringify( Germany ),
        stringify( Ghana ),
        stringify( Greece ),
        stringify( Grenada ),
        stringify( Guatemala ),
        stringify( Guinea ),
        stringify( Guinea_Bissau ),
        stringify( Guyana ),
        stringify( Haiti ),
        stringify( Honduras ),
        stringify( Hungary ),
        stringify( Iceland ),
        stringify( India ),
        stringify( Indonesia ),
        stringify( Iran ),
        stringify( Iraq ),
        stringify( Republic_of_Ireland ),
        stringify( Italy ),
        stringify( Ivory_Coast ),
        stringify( Jamaica ),
        stringify( Japan ),
        stringify( Jordan ),
        stringify( Kazakhstan ),
        stringify( Kenya ),
        stringify( Kiribati ),
        stringify( Korea_North ),
        stringify( Korea_South ),
        stringify( Kosovo ),
        stringify( Kuwait ),
        stringify( Kyrgyzstan ),
        stringify( Laos ),
        stringify( Latvia ),
        stringify( Lebanon ),
        stringify( Lesotho ),
        stringify( Liberia ),
        stringify( Libya ),
        stringify( Liechtenstein ),
        stringify( Lithuania ),
        stringify( Luxembourg ),
        stringify( Macedonia ),
        stringify( Madagascar ),
        stringify( Malawi ),
        stringify( Malaysia ),
        stringify( Maldives ),
        stringify( Mali ),
        stringify( Malta ),
        stringify( Marshall_Islands ),
        stringify( Mauritania ),
        stringify( Mauritius ),
        stringify( Mexico ),
        stringify( Micronesia ),
        stringify( Moldova ),
        stringify( Monaco ),
        stringify( Mongolia ),
        stringify( Montenegro ),
        stringify( Morocco ),
        stringify( Mozambique ),
        stringify( Myanmar ),
        stringify( Namibia ),
        stringify( Nauru ),
        stringify( Nepal ),
        stringify( Netherlands ),
        stringify( New_Zealand ),
        stringify( Nicaragua ),
        stringify( Niger ),
        stringify( Nigeria ),
        stringify( Norway ),
        stringify( Oman ),
        stringify( Pakistan ),
        stringify( Palau ),
        stringify( Panama ),
        stringify( Papua_New_Guinea ),
        stringify( Paraguay ),
        stringify( Peru ),
        stringify( Philippines ),
        stringify( Poland ),
        stringify( Portugal ),
        stringify( Qatar ),
        stringify( Romania ),
        stringify( Russian_Federation ),
        stringify( Rwanda ),
        stringify( St_Kitts_Nevis ),
        stringify( St_Lucia ),
        stringify( Saint_Vincent_the_Grenadines ),
        stringify( Samoa ),
        stringify( San_Marino ),
        stringify( Sao_Tome_Principe ),
        stringify( Saudi_Arabia ),
        stringify( Senegal ),
        stringify( Serbia ),
        stringify( Seychelles ),
        stringify( Sierra_Leone ),
        stringify( Singapore ),
        stringify( Slovakia ),
        stringify( Slovenia ),
        stringify( Solomon_Islands ),
        stringify( Somalia ),
        stringify( South_Africa ),
        stringify( South_Sudan ),
        stringify( Spain ),
        stringify( Sri_Lanka ),
        stringify( Sudan ),
        stringify( Suriname ),
        stringify( Swaziland ),
        stringify( Sweden ),
        stringify( Switzerland ),
        stringify( Syria ),
        stringify( Taiwan ),
        stringify( Tajikistan ),
        stringify( Tanzania ),
        stringify( Thailand ),
        stringify( Togo ),
        stringify( Tonga ),
        stringify( Trinidad_Tobago ),
        stringify( Tunisia ),
        stringify( Turkey ),
        stringify( Turkmenistan ),
        stringify( Tuvalu ),
        stringify( Uganda ),
        stringify( Ukraine ),
        stringify( United_Arab_Emirates ),
        stringify( United_Kingdom ),
        stringify( United_States ),
        stringify( Uruguay ),
        stringify( Uzbekistan ),
        stringify( Vanuatu ),
        stringify( Vatican_City ),
        stringify( Venezuela ),
        stringify( Vietnam ),
        stringify( Yemen ),
        stringify( Zambia ),
        stringify( Zimbabwe )
    };

    /// @brief Inline function to convert a CountryEnum input to string output
    /// @param country 
    /// @return Name of the country refered to by country
    inline string CountryEnum_to_string(CountryEnum country) {
        return countryEnum_to_string[(int)country];
    }

    /// @brief Binary search to find the string that matches the enum name to convert string to Enum.
    /// @param str The string to be converted
    /// @param low Left hand bound of the binary search
    /// @param high Right hand bound of the binary search
    /// @return CounrtyEnum based on the given string country
    CountryEnum binarySearch(string str, int low, int high) {
        if (low > high)
            return (CountryEnum) 0; 
        else {
            int mid = (low + high) / 2;
            if (str == CountryEnum_to_string((CountryEnum) mid))     // str is found
                return (CountryEnum)mid;
            else if (str > CountryEnum_to_string((CountryEnum) mid)) // str is on the right side
                return binarySearch(str, mid + 1, high);
            else                                                     // str is on the left side
                return binarySearch(str, low, mid - 1);
        }
    }

    /// @brief Converts a string to corresponding CountryEnum value
    /// @param str The string to be converted
    /// @return CounrtyEnum based on the given string country
    CountryEnum string_to_CountryEnum(string str) {
        return binarySearch(str, 0, size - 1);
    } 
}

#endif